Controllers films users
i2GR/java-filmorate pull request #1
Opened 2023-01-20 19:01 UTC by i2GR

SP9 FP initial by Igor I.

2023-01-21 17:58 UTC, AnastasiyaFomkina requested changes
Хорошая работа - молодец 👍
Из общих комментариев: нужно поправить весь проект по `code-style`: это легко можно сделать, если использовать горячие клавиши в IDEA [Ctrl+Alt+L](https://www.jetbrains.com/idea/guide/tips/reformat-file/)
Важно не использовать сокращения и однобуквенные переменные в проекте, так как в коммерческой разработке такой подход считается code-smell и делает код менее читаемым

2023-01-21 17:58 UTC, afomkina commented on pom.xml
> +	<description>YP SP9 final project (ii)</description>
Лучше добавить в описание красткий тезис чем занимается приложение

2023-01-21 17:58 UTC, afomkina commented on .gitignore
> +**/target/
Нужно добавить игнорирование для `.mvn/wrapper`, `mvnw` и `mvnw.cmd`

2023-01-21 17:58 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @PostMapping("")
Если не требуется дополнить ссылку запроса, то лучше убрать параметры у аннотации:
```suggestion
    @PostMapping
```
Поправь, пожалуйста, во всех методах контроллеров

2023-01-21 17:58 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Setter
Здесь сеттер не нужен, лучше сделать переменную `customValidation` финальной.

2023-01-21 17:58 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @Setter
Нужно поправить как в классе FilmController

2023-01-21 17:58 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (customValidation) film = FilmValidator.validate(film);
Оставлять код, чтобы тесты проходили корректно - небезопасно. Нужно избавиться от дублирующий валидации

2023-01-21 17:58 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private boolean customValidation = false;
Лучше переименовать в 
```suggestion
    private boolean isValid = false;
```
Так код будет проще читать.

2023-01-21 17:58 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +import org.springframework.web.bind.annotation.*;
_Саморазвитие_
В коммерческой разработке не принято использовать `wildcard` в импортах.
Вот отличная [статья](https://struchkov.dev/blog/using-wildcard-imports-in-java/) почему и как настроить идею, чтобы избавиться от `*`
Кстати, в IDEA есть отличное сочетание клавиш `Ctrl + Alt + O` - при нажатии сочетания в нужном классе автоматически оптимизируются импорты и удаляются ненужные

2023-01-21 17:58 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @Pattern(regexp = "^\\w{1,}$", message = "User.login contains non letter o digit symbols")
🔥

2023-01-21 17:58 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @BirthDayPast
Можно заменить на уже реализованную аннотацию [@PastOrPresent ](https://www.baeldung.com/javax-validation#:~:text=%40Past%20and-,%40PastOrPresent,-validate%20that%20a) - она валидирует, что дата должна быть в прошлом или не позже, чем сейчас

2023-01-21 17:58 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +        fc.setCustomValidation(true);
Лучше не сеттеры или какой-то другой код специально для тестов. Такой подход делает программу менее безопасной и более уязвимой к нечаянным ошибкам

2023-01-21 17:58 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +        assertEquals(film,fc.addNewMovie(film));
Лучше продумать тест-кейсы таким образом, чтобы нам не потребовался какой-либо доступ к полям тестируемого класса.
Например, при добавлении фильма, метод `addNewMovie` возвращает нам объект `film`, если добавление прошло успешно или бросает ошибку, если нет.
В первом тесте можно передать методу фильм с корректно заполненными полями и проверить, что полученный фильм равен фильму, который мы передавали.
А во втором тесте, можно передать фильм с пустым полем "название" и проверить, что мы получили ошибку при выполнении данного метода. И так далее.
Перепиши, пожалуйста тесты таким образом, чтобы никак не взаимодействовать с полями тестируемого класса

2023-01-21 17:58 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +class UserControllerTest {
Поправь, пожалуйста, тесты для пользователей в соответствии с комментариями для тестов фильмов

2023-01-21 17:58 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    FilmController fc = new FilmController();
Не хватает модификатора доступа

2023-01-21 17:58 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/model/FilmTest.java
> +        List<String> violationMessages = constraintViolations.stream().map(v -> v.getMessage())
Стримы лучше бить на несколько строк, так их удобнее читать:
```suggestion
        List<String> violationMessages =
            constraintViolations.stream()
                .map(v -> v.getMessage())
                .collect(Collectors.toList());
```

2023-01-21 17:58 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/model/FilmTest.java
> +        List<String> violationMessages = constraintViolations.stream().map(v -> v.getMessage())
Можно вместо лямбды  `v -> v.getMessage()` 
использовать [method reference](https://www.baeldung.com/java-method-references): `ConstraintViolation::getMessage` 
везде, где это возможно

2023-01-21 17:58 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/model/FilmTest.java
> +    private static Film film;
Лучше не делать поле статичным, если того не требует контекст. Вот отличная [статья](https://medium.com/att-israel/should-you-avoid-using-static-ae4b58ca1de5), почему стоит избегать `static` везде, где это возможно

2023-01-21 17:58 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/model/UserTest.java
> +    private static User user;
Лучше убрать у поля `static`

2023-01-21 17:58 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/model/FilmTest.java
> +    @BeforeAll
Лучше отказаться от `@BeforeAll` и перенести инициализацию валидации в блок `@BeforeEach`.

2023-01-21 17:58 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/model/UserTest.java
> +    @BeforeAll
Лучше перенести в `@BeforeEach`

2023-01-21 17:58 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/validation/ValidationException.java
> +public class ValidationException extends Exception{
Исключение должно быть непроверяемым, следует наследовать этот класс от `RuntimeException`. Так же следует исключить его из заголовков всех методов, так как непроверяемые исключения не нужно в них указывать)

2023-01-21 17:58 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/validation/ValidationExceptionHandler.java
> +        log.warn(ve.getMessage());
Лучше добавить в логирование какое-либо сообщение о том, что произошло, а с помощью заполнителя (placeholder)`{}`, добавить в сообщение лог ошибки.
Например:
```suggestion
        log.warn("Некорректно заполнены поля body: {}", ve.getMessage());
```

2023-01-21 17:58 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/validation/ValidationExceptionHandler.java
> +            //throw new RuntimeException(e); // предложено идеей
Лучше удалять ненужный код, а не комментировать его, так как код становится менее читаемым и отвлекает разработчиков. Если он вдруг потребуется его всегда можно восстановить из гита

2023-01-21 17:58 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/validation/ValidationExceptionHandler.java
> +public class ValidationExceptionHandler extends ResponseEntityExceptionHandler {
Лучше вынести кастомные ошибки и хэндлер в отдельный пакет

2023-01-21 17:58 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/validation/StringValidator.java
> +public class StringValidator {
Лучше удалить этот класс, так как поля проверяются с помощью аннотаций валидации, не стоит хранить дублирующие методы

2023-01-21 17:58 UTC, AnastasiyaFomkina commented on pom.xml
> +			<artifactId>junit-platform-suite-commons</artifactId>
Лишняя зависимость

2023-01-21 17:58 UTC, AnastasiyaFomkina commented on pom.xml
> +			<artifactId>hibernate-validator</artifactId>
Лишняя зависимость

2023-01-23 18:49 UTC, i2GR commented
Спасибо за ревью!
замечания исправлены но есть пара вопросов (в комментах)
- вопрос про обобщенные директивы импорта (в чистом коде, наоборот, говорится, что можно)
- не очень понятно, как в рамках одного теста без доступа к полям простым способом создать копию фильма (или юзера) с измененными полями - модифицированный объект, чтобы его обновить в контроллере.
прямой путь - новый экземпляр с частично повторяющимися полями
- почему лучше исключение должно быть непроверяемым?

2023-01-23 18:49 UTC, i2GR commented on pom.xml
> +			<artifactId>hibernate-validator</artifactId>
и этого я не знал...

2023-01-23 18:49 UTC, i2GR commented on pom.xml
> +			<artifactId>junit-platform-suite-commons</artifactId>
этого я не знал...

2023-01-23 18:49 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/controller/validation/StringValidator.java
> +public class StringValidator {
+
он не нужен как и все "ручные" валидаторы

2023-01-23 18:49 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/controller/validation/ValidationExceptionHandler.java
> +public class ValidationExceptionHandler extends ResponseEntityExceptionHandler {
в пакете controller.validation после удаления "ручных" валидаторов остались только кастомное исключение и валидоры через аннотации и сами аннотация (сама аннтоация -одна осталась)

2023-01-23 18:49 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/controller/validation/ValidationExceptionHandler.java
> +            //throw new RuntimeException(e); // предложено идеей
исправлено

2023-01-23 18:49 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/controller/validation/ValidationExceptionHandler.java
> +        log.warn(ve.getMessage());
исправлено

2023-01-23 18:49 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/controller/validation/ValidationException.java
> +public class ValidationException extends Exception{
исправлено, но
ВОПРОС: почему лучше исключение должно быть непроверяемым?

2023-01-23 18:49 UTC, i2GR commented on src/test/java/ru/yandex/practicum/filmorate/model/UserTest.java
> +    @BeforeAll
исправлено

2023-01-23 18:49 UTC, i2GR commented on src/test/java/ru/yandex/practicum/filmorate/model/FilmTest.java
> +    @BeforeAll
исправлено

2023-01-23 18:49 UTC, i2GR commented on src/test/java/ru/yandex/practicum/filmorate/model/UserTest.java
> +    private static User user;
исправлено

2023-01-23 18:49 UTC, i2GR commented on src/test/java/ru/yandex/practicum/filmorate/model/FilmTest.java
> +    private static Film film;
исправлено

2023-01-23 18:49 UTC, i2GR commented on src/test/java/ru/yandex/practicum/filmorate/model/FilmTest.java
> +        List<String> violationMessages = constraintViolations.stream().map(v -> v.getMessage())
исправлено

2023-01-23 18:49 UTC, i2GR commented on src/test/java/ru/yandex/practicum/filmorate/model/FilmTest.java
> +        List<String> violationMessages = constraintViolations.stream().map(v -> v.getMessage())
исправлено

2023-01-23 18:49 UTC, i2GR commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    FilmController fc = new FilmController();
тесты переписаны (заново)

2023-01-23 18:49 UTC, i2GR commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +class UserControllerTest {
исправлено... (надеюсь)

2023-01-23 18:49 UTC, i2GR commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +        assertEquals(film,fc.addNewMovie(film));
если я правильно понял ,то в тесты добавлены билдеры фильмов/юзеров
в каждом тесте используется новый экз. фильма/юзера из билдера
ВОПРОС:
не очень понятно, как в рамках одного теста без доступа к полям простым способом создать копию фильма (или юзера) с измененными полями - модифицированный объект, чтобы его обновить в контроллере.
прямой путь - новый экземпляр с частично повторяющимися полями

2023-01-23 18:49 UTC, i2GR commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +        fc.setCustomValidation(true);
действительно... спасибо.
я об этом недостаточно подумал, специально введ поле customValidation, но только потому что:
а) раз уж сначала был создан ручной валидатор, нужно было предусмотреть "демонстрацию его работы", по крайней мере в тестах
б) создание поля-статуса было наилегчайшим путем включить его в класс контроллера и убрать его ,т.к.
в) использование валидации через аннотации делает ненужным ручную валидацию и все что с ней связано включая тесты нужно будет после замечаний убирать. А замечания были ожидаемы...

2023-01-23 18:49 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @BirthDayPast
какая то магия :eyes:, если оно само валидирует поле типа LocalDate c незаданным форматом

2023-01-23 18:49 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @Pattern(regexp = "^\\w{1,}$", message = "User.login contains non letter o digit symbols")
даже добавлять в коммент :fire: приходится учиться
опечатка "o digit" одна из причин переписать тесты

2023-01-23 18:49 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +import org.springframework.web.bind.annotation.*;
раз принято - значит принято.
я сам не люблю неопределенности:)
хотя в приведенной статье говорится об обратном со ссылкой на "чистый код":
J1: Используйте обобщенные директивы импорта "даже в унаследованном коде лучше
применять обобщенный импорт". Мартин Р. М29 Чистый код: создание, анализ и рефакторинг. - Спб.: Питер, 2019. стр 347

2023-01-23 18:49 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private boolean customValidation = false;
boolean customValidation используется только для тестов ручной валидации, поэтому в контексте других замечаний это поле удалено из классов

2023-01-23 18:49 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (customValidation) film = FilmValidator.validate(film);
+

2023-01-23 18:49 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @Setter
исправлен code-style (пустые строки)

2023-01-23 18:50 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Setter
boolean customValidation используется только для тестов ручной валидации, поэтому в контексте других замечаний это поле удалено из классов

2023-01-23 18:50 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @PostMapping("")
недосмотрел...

2023-01-23 18:50 UTC, i2GR commented on .gitignore
> +**/target/
спасибо.
дополнительно прочитано, почему так...

2023-01-23 18:50 UTC, i2GR commented on pom.xml
> +	<description>YP SP9 final project (ii)</description>
добавлено описание в тег description

2023-01-24 09:11 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +import org.springframework.web.bind.annotation.*;
Да, но ниже расписана мысль автора статьи, что большое количество импортов сейчас не является проблемой, так как среда разработки скрывает это полотно от разработчиков, пока ему не потребуется туда заглянуть. А вот если потребуется заглянуть, гораздо удобнее и проще понимать, какие импорты были добавлены и используются данным классом, когда они все явно прописаны, а не схлопнуты в wildcard

2023-01-24 09:15 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +        assertEquals(film,fc.addNewMovie(film));
Тут, наверное, я больше хотела обратить внимание на валидацию, которая была отставлена для тестов и предложить варианты решения, как можно обойтись без нее. 
Пример выше предлагает создать экземпляр класса `FilmController` и проверять сами методы, на разных данных по фильмам и юзерам. 
Видимо, слишком сильно мне запало в душу это поле customValidation 😁

2023-01-24 09:29 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/validation/ValidationException.java
> +public class ValidationException extends Exception{
Потому что подобный тип ошибок обрабатывается JVM во время работы программы и никак не влияет на компиляцию. Второй момент - их не нужно явно отлавливать и обрабатывать - меньше шаблонного кода и проблем, которые могу возникнуть по невнимательности. Ну и самое мое любимое - так принято в коммерческой разработке 😁
Вообще тема очень холиварная и есть два прямо противоположных мнения, как правильно делать.
Но так как у нас в проекте не заложена какая-либо сложная логика обработки ошибок валидации, я считаю, что лучше воспользоваться методом наименьшего сопротивления и не плодить множественные try-catch/ throws, когда это не нужно

2023-01-24 09:38 UTC, AnastasiyaFomkina commented
> Спасибо за ревью! замечания исправлены но есть пара вопросов (в комментах)
> 
> * вопрос про обобщенные директивы импорта (в чистом коде, наоборот, говорится, что можно)
> * не очень понятно, как в рамках одного теста без доступа к полям простым способом создать копию фильма (или юзера) с измененными полями - модифицированный объект, чтобы его обновить в контроллере.
>   прямой путь - новый экземпляр с частично повторяющимися полями
> * почему лучше исключение должно быть непроверяемым?

Ответила более подробно в тредах под самими вопросами, здесь продублирую тезисно:

1) Самая большая проблема wildcard в том, что можно легко пропустить конфликт имен, а потом долго и упорно искать почему же не запускается программа - это очень неприятно и часто отнимает много времени
2) Тут скорее просто не там тегнула комментарий и немного тебя сбила с мысли, этот комментарий больше был про поле оставленное для тестирование
3) В нашем случае нет смысла в проверяемом исключении, так как у нас нет сложной логики обработки ошибок валидации

2023-01-24 10:03 UTC, AnastasiyaFomkina requested changes
Молодец, что оставляешь вопросы и стараешься разбираться 👍

2023-01-24 10:03 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/validation/FixedValues.java
> +    public static final int MOVIE_DESCR_LENGTH = 200;
Поле больше нигде не используется, поэтому его лучше удалить

2023-01-24 10:03 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/BasicController.java
> +        log.info(String.format("requested %s to add", dtoName));
При логировании параметров, лучше использовать заполнитель(placeholder) `{}`. На его место автоматически подставится нужное значение и не придется использовать дополнительный метод форматирования:
```suggestion
        log.info("requested {} to add", dtoName);
```

2023-01-24 10:03 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/BasicController.java
> +        throw new ValidationException(dtoName + " to add already exists");
А вот тут удобнее будет использовать форматирование, а не конкатенацию

2023-01-24 10:03 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    LocalDate birthday;
Не хватает модификатора доступа

2023-01-24 10:03 UTC, afomkina commented on src/test/java/ru/yandex/practicum/filmorate/controller/ControllerTest.java
> +    @Test()
Лишние скобочки

2023-01-24 10:03 UTC, afomkina commented on src/test/java/ru/yandex/practicum/filmorate/controller/ControllerTest.java
> +        assertThrows(Exception.class, () -> controller.addNew(null));
Лучше проверять, что получили конкретное исключение, которое и ждем, как в тесте ниже, а не обобщенный `Exception`

2023-01-24 10:03 UTC, afomkina commented on src/test/java/ru/yandex/practicum/filmorate/controller/ControllerTest.java
> +        assertEquals(0, controller.getAll().size());
Можно упростить проверку до:
```suggestion
          assertTrue(controller.getAll().isEmpty());
```
Метод `isEmpty()` возвращает `true`, если `размер списка == 0` или `false` в любом другом случае

2023-01-24 10:03 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    public FilmControllerTest() {
Лучше сделать `private`, так как больше нигде не понадобится.

2023-01-24 10:03 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +    public UserControllerTest() {
Лучше сделать `private`

2023-01-24 16:57 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/controller/validation/FixedValues.java
> +    public static final int MOVIE_DESCR_LENGTH = 200;
а может быть лучше исправить таким образом чтобы избавиться от "магических чисел":
- и использовать константу в аннотации
- использовать константу в тестах длины поля Description (и переименовать методы)

`class Film 
//
    @NotBlank(message = "Film.description is blank")
    @Size(max = FixedValues.MAX_MOVIE_DESCR_LENGTH, message = "Film.description too long")
    private String description;
//`

2023-01-24 16:58 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/controller/BasicController.java
> +        log.info(String.format("requested %s to add", dtoName));
недосмотрел... стандартная же фича логгера

2023-01-24 16:58 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/controller/BasicController.java
> +        throw new ValidationException(dtoName + " to add already exists");
исправлено

2023-01-24 17:00 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    LocalDate birthday;
эх, ошибка уровня первый спринт:)

2023-01-24 17:00 UTC, i2GR commented on src/test/java/ru/yandex/practicum/filmorate/controller/ControllerTest.java
> +    @Test()
как так то....

2023-01-24 17:00 UTC, i2GR commented on src/test/java/ru/yandex/practicum/filmorate/controller/ControllerTest.java
> +        assertThrows(Exception.class, () -> controller.addNew(null));
недосмотрел...

2023-01-24 17:00 UTC, i2GR commented on src/test/java/ru/yandex/practicum/filmorate/controller/ControllerTest.java
> +        assertEquals(0, controller.getAll().size());
да так проще. действительно.
просто я встречал ситуации ,когда IDEA часто предлагала assertEquals() вместо assertTrue()
сейчас я наверное понял почему. кажется она настолько умна, чтобы предусматривать, что будет легче читаться.
assertTrue(controller.getAll().isEmpty()) здесь получается легче человеко-читаемо. буду проверять дальше эту теорию

2023-01-24 17:00 UTC, i2GR commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    public FilmControllerTest() {
это фиаско

2023-01-24 17:01 UTC, i2GR commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +    public UserControllerTest() {
надо быть внимательнее

2023-01-24 17:02 UTC, i2GR commented
Спасибо за ревью №2
прямо стыдно :) за часть очень грубых ошибок по невнимательности

2023-01-25 13:32 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/validation/FixedValues.java
> +    public static final int MOVIE_DESCR_LENGTH = 200;
Хорошая идея 👍

2023-01-25 13:37 UTC, AnastasiyaFomkina approved these changes
Отлично справился 🔥

2023-02-05 00:17 UTC, merged