Add friends likes
i2GR/java-filmorate pull request #2
Opened 2023-02-05 00:10 UTC by i2GR

финальный проект спринта 10

2023-02-06 15:08 UTC, AnastasiyaFomkina requested changes

2023-02-06 15:08 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/BasicController.java
> +    protected final EntityServable<T> service;
Так как `EntityServable` интерфейс - инжектить его с помощью `@Autowired `не получится, потому что он не является бином. Сейчас все работает корректно, потому что он инжектится с помощью `@RequiredArgsConstructor`. 
`@Autowired` - лишний, нужно удалить

2023-02-06 15:08 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/LikeController.java
> +        Integer count = countParam.isEmpty() ? Constants.DEFAULT_POPULAR_FILMS_AMOUNT : countParam.get();
Можно переписать в функциональном стиле:
```suggestion
        Integer count = countParam.orElse(Constants.DEFAULT_POPULAR_FILMS_AMOUNT);
```
Вот отличная подробная [статья](https://habr.com/ru/post/346782/) про `Optional`

2023-02-06 15:08 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/LikeController.java
> +    @Autowired
Лишний, так как есть `@RequiredArgsConstructor`

2023-02-06 15:08 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FriendsContoller.java
> +    @Autowired
Лишний, так как есть `@RequiredArgsConstructor`

2023-02-06 15:08 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/exception/ErrorResponse.java
> +    String description;
Не хватает модификаторов доступа у полей класса

2023-02-06 15:08 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/exception/ErrorResponse.java
> +    public ErrorResponse(String error, String description) {
Можно заменить аннотацией [@AllArgsConstructor](https://habr.com/ru/company/piter/blog/676394/#:~:text=%40NoArgsConstructor%2C%C2%A0%40RequiredArgsConstructor%2C-,%40AllArgsConstructor,-%D0%9A%D0%BE%D0%B3%D0%B4%D0%B0%20%D0%BA%D0%BB%D0%B0%D1%81%D1%81%20%D0%B0%D0%BD%D0%BD%D0%BE%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD)

2023-02-06 15:08 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/exception/service/UserServiceException.java
> +    private User user;
Может быть [final](https://vertex-academy.com/tutorials/ru/modifikator-final/)

2023-02-06 15:08 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/exception/storage/StorageDuplicateException.java
> +    Object object;
Не хватает модификатора доступа

2023-02-06 15:08 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/activity/FriendPair.java
> +        if (userId.longValue() == friendIdOne.longValue()) return Optional.of(friendIdTwo);
Лучше выделять блок кода после условия с помощью фигурных скобочек `{}`. Так код выглядит более структурно и его проще читать
```suggestion
        if (userId.longValue() == friendIdOne.longValue()) {
            return Optional.of(friendIdTwo);
        }
```

2023-02-06 15:08 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/activity/FriendPair.java
> +        if (userId.longValue() == friendIdTwo.longValue()) return Optional.of(friendIdOne);
```suggestion
        if (userId.longValue() == friendIdTwo.longValue()) { 
            return Optional.of(friendIdOne);
        }
```

2023-02-06 15:08 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/BasicEntityService.java
> +public abstract class BasicEntityService<T extends Entity> implements EntityServable<T> {
На самом деле, данный абстрактный класс, как и абстрактный класс для контроллеров - избыточность. Я бы их удалила, потому что код становится слишком сложным для восприятия, и не несет никаких плюсов. Если реализация сервисов фильмов и пользователей сейчас схожа, то не значит, что завтра не придет какое-либо изменение, которое сломает данную парадигму. Лучше оставить интерфейс для контроллеров и сервисов, в котором будут базовые методы по созданию/удалению/получению. А реализацию писать в классах, которые будут реализовывать этот интерфейс

2023-02-06 15:08 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/model/activity/LikeTest.java
> +        assertTrue(true);
Странная проверка, нужно либо доделать, либо удалить

2023-02-07 21:11 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/controller/BasicController.java
> +    protected final EntityServable<T> service;
исправлено

2023-02-07 21:12 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/controller/LikeController.java
> +        Integer count = countParam.isEmpty() ? Constants.DEFAULT_POPULAR_FILMS_AMOUNT : countParam.get();
исправлено
спасибо

2023-02-07 21:12 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/controller/LikeController.java
> +    @Autowired
исправлено

2023-02-07 21:12 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/controller/FriendsContoller.java
> +    @Autowired
исправлено

2023-02-07 21:12 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/exception/ErrorResponse.java
> +    String description;
исправлено
ошибка копи-пасты:(

2023-02-07 21:12 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/exception/service/UserServiceException.java
> +    private User user;
исправлено

2023-02-07 21:12 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/exception/storage/StorageDuplicateException.java
> +    Object object;
исправлено

2023-02-07 21:12 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/model/activity/FriendPair.java
> +        if (userId.longValue() == friendIdOne.longValue()) return Optional.of(friendIdTwo);
надо так надо :)

2023-02-07 21:12 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/model/activity/FriendPair.java
> +        if (userId.longValue() == friendIdTwo.longValue()) return Optional.of(friendIdOne);
и здесь...
и в public boolean equals(Object o) для единообразия

2023-02-07 21:12 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/service/BasicEntityService.java
> +public abstract class BasicEntityService<T extends Entity> implements EntityServable<T> {
т.е один интерфейс?
У меня почему-то в голове навязчивая идея не писать повторяющегося кода.
т.к. валидацию аргументов методов стоит проводить не только в слое контроллеров но и в слое сервисов,
я метод перенаправления спринг-исключения `MethodArgumentNotValidException` сделал дефолтным в интерфейсе r`u.yandex.practicum.filmorate.utils.ValidThrowable`, который может быть общим для любого слоя (контроллера или сервиса)
контроллеры его имплементируют
и имплементируют единый интерфейс `ru.yandex.practicum.filmorate.BasicModelHandling` с базовыми методами добавления/чтения/модификации/удаления

2023-02-07 21:12 UTC, i2GR commented on src/test/java/ru/yandex/practicum/filmorate/model/activity/LikeTest.java
> +        assertTrue(true);
т.к. тест простой, и класс простой я выбрал удалить

2023-02-07 21:12 UTC, i2GR commented
Спасибо за ревью

2023-02-08 10:06 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/BasicEntityService.java
> +public abstract class BasicEntityService<T extends Entity> implements EntityServable<T> {
Понимаю, как хочется не писать повторяющийся код, но будем честны, между фильмами и пользователями нет ничего общего, поэтому лучше не стараться объединить вещи, которые не подлежат объединению. Чем больше лишний абстракций в коде, тем более громоздким он выглядит и тем сложнее его поддерживать. Например, общий класс для тестов в 7 спринте был оправдан, так как у нас было две разные реализации одного и того же интерефейса, только разными способами, с помощью сохранения в память программы и в файл. Логика работы списка задач была одинаковая, но отличалась реализация способов хранения, поэтому тесты можно было объединить в абстрактный класс и уже наследовать разные реализации от него.

2023-02-08 10:15 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/BasicEntityService.java
> +public abstract class BasicEntityService<T extends Entity> implements EntityServable<T> {
Для того, чтобы отлавливать исключения по всему проекту проще реализовать [GlobalErrorHander](https://www.codejava.net/frameworks/spring-boot/global-exception-handler-examples), нежели создавать свои интерфейсы и общие реализации.

К сожалению, чем сложнее выглядит код - тем меньше желания у работодателя в нем разбираться. Может быть он будет выглядеть чуть менее оригинально, но будет сразу понятно, как оно работает.

Кстати, если хочешь максимально избавиться от повторяющегося кода, предлагаю подумать в сторону [рефакторинга и паттернов проектирования](https://refactoring.guru/ru/design-patterns) (сайт может не открываться без впн). Это стандартизированные подходы по улучшению качества кода, принятые во всех компаниях. Их часто спрашивают на собеседованиях и используют в работе

2023-02-08 10:16 UTC, AnastasiyaFomkina approved these changes

2023-02-08 10:19 UTC, AnastasiyaFomkina commented
Работу я принимаю, так как она выполнена корректно и хорошо. Выше подробно описала свои опасения насчет того, чтобы все выносить в абстракции. Предлагаю к следующему спринту программу немного упросить, почитать на досуге про паттерны и рефакторинг и попробовать применить новые знания в деле :)

2023-02-24 15:31 UTC, merged