Add database
i2GR/java-filmorate pull request #3
Opened 2023-03-04 13:54 UTC by i2GR

2023-03-05 09:40 UTC, AnastasiyaFomkina requested changes

2023-03-05 09:40 UTC, AnastasiyaFomkina commented on pom.xml
> +			<artifactId>spring-boot-starter-data-jpa</artifactId>
Так как в данной работе jpa не используется, лучше удалить ненужную зависимость

2023-03-05 09:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/DBFilmStorage.java
> +/*    private List<Genre> getGenresById(Long filmId) {
Если метод ненужен, то стоит его удалить, а не комментировать

2023-03-05 09:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/DBFilmStorage.java
> +/*    private Map<Long, List<String>> getGenresCommon() {
Нужно удалить

2023-03-05 09:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/DBFilmStorage.java
> +        for (Film film : films) {
Нужно переписать с помощью [stream api](https://habr.com/ru/company/otus/blog/658999/)

2023-03-05 09:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/DBFilmStorage.java
> +            // empty: goto return;
Не стоит оставлять пустые блоки catch, в случае ошибки, будет непонятно, куда пошел процесс. Если нет желание пробрасывать бизнесовую ошибку, то стоит хотя бы залогировать поведение программы, чтобы понимать что и где произошло

2023-03-05 09:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/DBFilmStorage.java
> +            Long newFilmId = keyHolder.getKey().longValue();
Нужно проверять, что `keyHolder.getKey() =! null`, прежде, чем получать `longValue()`. Тогда ненужно будет специально отлавливать `NullPointerException`

2023-03-05 09:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/DBGenreStorage.java
> +        //SqlRowSet tst = jdbcTemplate.queryForRowSet("SELECT COUNT(id) AS cnt FROM film_genres WHERE film_id = ?;", filmId);
Удали, пожалуйста, весь закомментированный код по всему проекту

2023-03-05 09:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/DBUserStorage.java
> +            Long newUserId = keyHolder.getKey().longValue();
Нужно поправить по комментариям к классу `DBFilmStorage`

2023-03-05 09:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/film/DBFilmService.java
> +    @Qualifier("filmDBStorage")
_Интересные факты_
В новых версиях спринга `@Qualifier` уже не обязателен. Можно заменить название параметра на название нужного бина и спринг автоматически подставит нужную реализацию :)

2023-03-05 09:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/film/DBFilmService.java
> +    private final FilmStorage filmStorage;
```suggestion
    private final FilmStorage filmDBStorage;
```

2023-03-05 09:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/film/DBFilmService.java
> +        for (Film film : filmList) {
Нужно переписать с помощью stream api

2023-03-05 09:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/friend/DBFriendService.java
> +    @Autowired
Лишний, так как есть `@RequiredArgsConstructor`

2023-03-05 09:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserServable.java
> +                //log.info("User.name received is empty. User renamed based on Login");
Нужно удалить

2023-03-05 09:40 UTC, AnastasiyaFomkina commented on src/main/resources/applicationContext.xml
> +    <bean id="UserService" class="ru.yandex.practicum.filmorate.service.user.InMemoryUserService" autowire="constructor"></bean-->
Данный файл - лишний, нужно удалить. Все настройки бинов проекта можно сделать с помощью аннотаций

2023-03-05 09:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/DBFriendsStorage.java
> +        String sqlQuery = "SELECT * FROM users WHERE id IN " + subQuery + ";";
Нужно избавиться от множественных вложенных подзапросов

2023-03-06 18:15 UTC, i2GR commented on pom.xml
> +			<artifactId>spring-boot-starter-data-jpa</artifactId>
удалено.
но я добавил  mave-dependency-plugin, чтобы смотреть лишнее

2023-03-06 18:16 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/dao/DBFriendsStorage.java
> +        String sqlQuery = "SELECT * FROM users WHERE id IN " + subQuery + ";";
исправлено
(реализованы запросы с помощью INNER JOIN или разбит запрос на два с обработкой в слое сервиса (для поиска общих друзей)

2023-03-06 18:16 UTC, i2GR commented on src/main/resources/applicationContext.xml
> +    <bean id="UserService" class="ru.yandex.practicum.filmorate.service.user.InMemoryUserService" autowire="constructor"></bean-->
исправлено

2023-03-06 18:16 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/service/friend/DBFriendService.java
> +    @Autowired
исправлено

2023-03-06 18:16 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/service/film/DBFilmService.java
> +        for (Film film : filmList) {
переписано через ForEach
вызов из genreService.getGenresForFilmById() исправлен на вызов
genreService.getFilmGenresCommon()
т.к. в первом случае происходит обращение в БД по количеству фильмов. во втором случае - только один запрос

2023-03-06 18:16 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/dao/DBFilmStorage.java
> +            // empty: goto return;
исправлено с переструктурированием обработки исключений и добавлением логирования

2023-03-06 18:16 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/dao/DBFilmStorage.java
> +        for (Film film : films) {
исправлено: см. далее
getFilmGenresCommon() перенесен в Genres-service/storage
в пачке, кажется, видел обсуждение, что каждый DAO должен заниматься своей таблицей. Жанры по логике, больше подходят к сервису с жанрами

2023-03-06 18:16 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/dao/DBFilmStorage.java
> +/*    private Map<Long, List<String>> getGenresCommon() {
аналогично. забыл вычистить
спасибо

2023-03-06 18:16 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserServable.java
> +                //log.info("User.name received is empty. User renamed based on Login");
тоже пропустил... спасибо

2023-03-06 18:17 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/service/friend/DBFriendService.java
> +    @Autowired
исправлено

2023-03-06 18:17 UTC, i2GR commented on src/main/java/ru/yandex/practicum/filmorate/service/film/DBFilmService.java
> +        for (Film film : filmList) {
исправлено с foreach

2023-03-06 18:20 UTC, i2GR commented
спасибо за ревью

2023-03-06 18:27 UTC, merged